export * from './basket.service';
import { BasketService } from './basket.service';
export * from './boxedPizza.service';
import { BoxedPizzaService } from './boxedPizza.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './personalDetails.service';
import { PersonalDetailsService } from './personalDetails.service';
export * from './pizza.service';
import { PizzaService } from './pizza.service';
export * from './sauce.service';
import { SauceService } from './sauce.service';
export * from './topping.service';
import { ToppingService } from './topping.service';
export const APIS = [BasketService, BoxedPizzaService, OrderService, PersonalDetailsService, PizzaService, SauceService, ToppingService];
