/**
 * REST API SPEC FOR MIX WEBAPP
 * REST API SPEC FOR MIX WEBAPP
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { PersonalDetails } from '../model/personalDetails';
import { PersonalDetailsWrapper } from '../model/personalDetailsWrapper';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PersonalDetailsService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add new personal details
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addPersonalDetails(body?: PersonalDetails, observe?: 'body', reportProgress?: boolean): Observable<PersonalDetails>;
    public addPersonalDetails(body?: PersonalDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonalDetails>>;
    public addPersonalDetails(body?: PersonalDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonalDetails>>;
    public addPersonalDetails(body?: PersonalDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<PersonalDetails>(`${this.basePath}/api/personalDetails/people`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete personal details
     * 
     * @param personID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePersonalDetails(personID: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deletePersonalDetails(personID: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deletePersonalDetails(personID: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deletePersonalDetails(personID: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personID === null || personID === undefined) {
            throw new Error('Required parameter personID was null or undefined when calling deletePersonalDetails.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (personID !== undefined && personID !== null) {
            queryParameters = queryParameters.set('personID', <any>personID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/personalDetails/people`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get all personal details
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPersonalDetails(observe?: 'body', reportProgress?: boolean): Observable<PersonalDetailsWrapper>;
    public getPersonalDetails(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonalDetailsWrapper>>;
    public getPersonalDetails(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonalDetailsWrapper>>;
    public getPersonalDetails(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<PersonalDetailsWrapper>(`${this.basePath}/api/personalDetails/people`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update personal details
     * 
     * @param personID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePersonalDetails(personID: number, body?: PersonalDetails, observe?: 'body', reportProgress?: boolean): Observable<PersonalDetails>;
    public updatePersonalDetails(personID: number, body?: PersonalDetails, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PersonalDetails>>;
    public updatePersonalDetails(personID: number, body?: PersonalDetails, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PersonalDetails>>;
    public updatePersonalDetails(personID: number, body?: PersonalDetails, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (personID === null || personID === undefined) {
            throw new Error('Required parameter personID was null or undefined when calling updatePersonalDetails.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (personID !== undefined && personID !== null) {
            queryParameters = queryParameters.set('personID', <any>personID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<PersonalDetails>(`${this.basePath}/api/personalDetails/people/${encodeURIComponent(String(personID))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
