/**
 * REST API SPEC FOR MIX WEBAPP
 * REST API SPEC FOR MIX WEBAPP
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Sauce } from '../model/sauce';
import { SauceWrapper } from '../model/sauceWrapper';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SauceService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add new sauce
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addSauces(body?: Sauce, observe?: 'body', reportProgress?: boolean): Observable<Sauce>;
    public addSauces(body?: Sauce, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Sauce>>;
    public addSauces(body?: Sauce, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Sauce>>;
    public addSauces(body?: Sauce, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Sauce>(`${this.basePath}/api/sauce/sauces`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get sauces
     * 
     * @param sauceID 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSauces(sauceID: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteSauces(sauceID: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteSauces(sauceID: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteSauces(sauceID: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sauceID === null || sauceID === undefined) {
            throw new Error('Required parameter sauceID was null or undefined when calling deleteSauces.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sauceID !== undefined && sauceID !== null) {
            queryParameters = queryParameters.set('sauceID', <any>sauceID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/api/sauce/sauces`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get sauces
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSauces(observe?: 'body', reportProgress?: boolean): Observable<SauceWrapper>;
    public getSauces(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SauceWrapper>>;
    public getSauces(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SauceWrapper>>;
    public getSauces(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SauceWrapper>(`${this.basePath}/api/sauce/sauces`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update sauce
     * 
     * @param sauceID 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSauces(sauceID: number, body?: Sauce, observe?: 'body', reportProgress?: boolean): Observable<Sauce>;
    public updateSauces(sauceID: number, body?: Sauce, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Sauce>>;
    public updateSauces(sauceID: number, body?: Sauce, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Sauce>>;
    public updateSauces(sauceID: number, body?: Sauce, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sauceID === null || sauceID === undefined) {
            throw new Error('Required parameter sauceID was null or undefined when calling updateSauces.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sauceID !== undefined && sauceID !== null) {
            queryParameters = queryParameters.set('sauceID', <any>sauceID);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Sauce>(`${this.basePath}/api/sauce/sauces/${encodeURIComponent(String(sauceID))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
